# Site
repository: mateuspontesm/mateuspontesm.github.io
favicon: images/favicon.ico

# Personal info
name: Mateus Mota
title: Msc. Student and Research Assistant
email: mateuspontesm@outlook.com
website: www.github.com/mateuspontesm

# Social links
# twitter_username: facespics
github_username:  mateuspontesm
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: mateuspontesm
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile-mateus.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello there. My name's Mateus and I'm a Msc. student in Telecommunications Engineering, my research is focused in machine learning applied to 5G Networks, more specifically reinforcement learning based solutions applied in 5G scenarios.

  Aside from machine learning, I also have knowledge in Business Intelligence and Data Analysis from a graduate studies course.

  My main interests are Deep Reinforcement Learning, Link Adaptation techniques and PHY.

  I am most skilled in: <mark>Python</mark> and <mark>Matlab</mark>

# Projects Section
# projects_title: Publications

Experience Section
experience_title: Experience

Education Section
educaton_title: Education

# More Section
more_title: Skills
more_content: | # this will include new lines to allow paragraphs
  **Spoken Languages**: Portuguese (native), English (Full Professional), French (Professional).

  **Software**: LaTeX, Git, MATLAB, Office Suites, Tableau, Power BI.

  **Programming**: Python, SQL

  **Frameworks and Libraries**: Scikit-Learn, Keras, Pytorch, Bokeh


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
